# Generated by Django 3.1.2 on 2020-11-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20201128_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.png', upload_to='profilepictures'),
        ),
    ]
