# Generated by Django 3.1.2 on 2020-11-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_auto_20201128_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
