# Generated by Django 3.1.2 on 2020-11-29 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_auto_20201129_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
