# Generated by Django 3.1.2 on 2020-10-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201028_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(to='catalog.Developer'),
        ),
    ]
