# Generated by Django 3.1.2 on 2020-10-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201029_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='stock',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'Out of stock'), ('p', 'Pre-order'), ('c', 'Coming soon')], default='a', help_text='Game availability', max_length=1),
        ),
    ]
