# Generated by Django 3.1.2 on 2020-10-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201029_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinstance',
            old_name='stock',
            new_name='jimmy',
        ),
    ]
