# Generated by Django 3.1.2 on 2020-10-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201029_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinstance',
            old_name='jimmy',
            new_name='stock',
        ),
    ]
