# Generated by Django 3.1.2 on 2020-10-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201029_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
