# Generated by Django 3.1.2 on 2020-10-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201029_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
    ]
