# Generated by Django 3.1.2 on 2020-10-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20201029_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
