# Generated by Django 3.1.2 on 2020-10-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20201029_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('birth_of_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
