# Generated by Django 3.1.2 on 2020-10-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20201031_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_of_date',
            new_name='birth_date',
        ),
    ]
