# Generated by Django 3.1.2 on 2020-11-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_game_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(to='catalog.Developer'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='plataform',
        ),
        migrations.AddField(
            model_name='game',
            name='plataform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.plataform'),
        ),
    ]
