# Generated by Django 3.1.2 on 2020-11-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20201101_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
