# Generated by Django 3.1.2 on 2020-11-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20201101_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
    ]
