# Generated by Django 3.1.2 on 2020-11-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20201101_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
