# Generated by Django 3.1.2 on 2020-11-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20201101_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
